name: Mathics3 Doctest (Mathics3 doctest)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run: |
        sudo apt-get update -qq && sudo apt-get install -qq liblapack-dev llvm-dev tesseract-ocr remake
    - name: Install Mathics3 scanner without JSON
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Install JSON files
      run: |
        python -m mathics_scanner.generate.boxing_characters -o mathics_scanner/data/boxing-characters.json
        ls -l mathics_scanner/data/boxing-characters.json
        python -m mathics_scanner.generate.named_characters -o mathics_scanner/data/named-characters.json
        ls -l mathics_scanner/data/named-characters.json
        python -m mathics_scanner.generate.operators -o mathics_scanner/data/operators.json
        ls -l mathics_scanner/data/operators.json
    - name: Build Mathics3
      run: |
        # Until next Mathics3/mathics-core release is out...
        git clone -b add-unicode-box-characters --depth 1 https://github.com/Mathics3/mathics-core.git
        cd mathics-core/
        python -m pip install -e .[dev]
        cp -v ../mathics_scanner/data/boxing-characters.json mathics/data/boxing-characters.json
        cp -v ../mathics_scanner/data/named-characters.json mathics/data/named-characters.json
        cp -v ../mathics_scanner/data/operators.json mathics/data/operators.json
        cd ..
    - name: Run Mathics3 tests
      run: |
        remake -x check-mathics
